name: develop_deploy

on:
  push:
    branches: [develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  develop-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: ESLint cache
        uses: actions/cache@v3
        with:
          path: .eslintcache
          key: |
            ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.cjs') }}
          restore-keys: |
            ${{ runner.os }}-eslint-
      - name: Check typescript and lint
        run: pnpm check
      - name: Env
        run: |
          chmod 777 ./
          touch deploy_key
          echo "${{secrets.GG_SSH_PRIVATE_KEY}}" > deploy_key
          chmod 600 ./deploy_key
      - name: Build client
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          pnpm build:client
      - name: Deploy client
        run: |
          rsync -av  -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' --delete-delay ./packages/client/dist/client/* ${{ secrets.GG_SSH_URL }}:~/static/amarkdown-develop/
  main-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ~1.21
      - name: Env
        run: |
          chmod 777 ./
          touch deploy_key
          echo "${{secrets.GG_SSH_PRIVATE_KEY}}" > deploy_key
          chmod 600 ./deploy_key
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
      - name: Build server
        run: |
          cd cmd/server
          go build main.go
      - name: Deploy server
        run: |
          rsync -av  -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' ./cmd/server/main ${{ secrets.GG_SSH_URL }}:~/server/amarkdown-develop/
