name: main_deploy

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  main-client:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          bunx prisma generate
      - name: ESLint cache
        uses: actions/cache@v3
        with:
          path: .eslintcache
          key: |
            ${{ runner.os }}-eslint-${{ hashFiles('.eslintrc.cjs') }}
          restore-keys: |
            ${{ runner.os }}-eslint-
      - name: Check typescript and lint
        run: |
          bun run check
          bun run lint
      - name: Env
        run: |
          chmod 777 ./
          touch deploy_key
          echo "${{secrets.GG_SSH_PRIVATE_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          touch ./packages/client/.env.sentry-build-plugin
          echo "${{secrets.GG_SENTRY_AUTH_KEY}}" > ./packages/client/.env.sentry-build-plugin
          chmod 600 ./packages/client/.env.sentry-build-plugin
      - name: Build
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          bun run build
          cd build
          bun install
      - name: Deploy client
        run: |
          rsync -av  -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' --delete-delay ./build/* ${{ secrets.GG_SSH_URL }}:~/server/aisentence/
